### ISSUE TITLE
TIFF: Consider DEFLATE compression

### ISSUE THREAD

**Issue by mojodna** [mapzen/joerd#81]
@lossyrob did some benchmarking of the different compression options available to GDAL here: http://openterrain.tumblr.com/post/117553678231/gdal-compression-options-against-ned-data

For floating point data, the conclusion was that DEFLATE (with the floating point predictor) produces the smallest files at only a small time premium.

**Comment by zerebubuth** [comment]
I agree. I did some benchmarking before choosing `COMPRESS=LZW, PREDICTOR=2` and that was the best option for the data. Most likely, the difference in best compression options is because the data is `Int16` rather than `Float32` as you mention in #80. We can come back to what compression options to use if we change the data type.
